#!/bin/bash


## Get Parameters
PACKAGE=$1
MESSAGE=$2
DELIM=$3
FIELDS=$4
METAS=$5

PRIMARY="PRIMARY"
OTHER="OTHER"

## Define the filename
FILE_NAME="./protos/$MESSAGE.proto"

## Will write to FILE_NAME
function write {
    echo -e $1 >> "$FILE_NAME"
}

## Adds a blank newline to FILE_NAME
function newline {
    write ""
}

function writeFields {
    count=1
    index=1
    IFS=',' read -ra FIELD_ARR <<< $1
    IFS=',' read -ra META_ARR <<< $2
    DELIM=$3
    KEY_TYPE=$4

    for field in ${FIELD_ARR[@]}
    do
        
        VAR=$field
        
        META_SET=${META_ARR[index]}

        IFS=$DELIM read -ra META <<< $META_SET

        SQL_TYPE=${META[1]}
        NULLABLE=${META[2]}
        KEY=${META[3]}

        PROTO_TYPE=`./sql-to-prototype.sh $SQL_TYPE $VAR $NULLABLE $KEY`
        if [ ! "$KEY" = "PRI" ] && [ "$KEY_TYPE" = "$OTHER" ]
        then
            write "\t$PROTO_TYPE $VAR = $count;"
            count=$((count+1))
        fi

        if [ "$KEY" = "PRI" ] && [ "$KEY_TYPE" = "$PRIMARY" ]
        then
            write "\t$PROTO_TYPE $VAR = $count;"
            count=$((count+1))
        fi

        index=$((index+1))

        
    done
}


## Make the protos folder if it does not exist
mkdir -p "./protos/"

## Delete the previous version of this file if it exists
rm -f $FILE_NAME
## Create the file
touch $FILE_NAME

CLASS_NAME=${MESSAGE^}

write "//--AUTOGENERATED PROTOFILE $FILENAME FOR $MESSAGE--"
newline
newline
write "syntax = \"proto2\";"
newline
write "option java_multiple_files = true;"
write "option java_package = \"life.genny.model.grpc\";"
write "option java_outer_classname = \"${CLASS_NAME}Proto\";"
newline
write "package $PACKAGE;"
newline
newline
write "message ${MESSAGE}_key {"
writeFields $FIELDS $METAS $DELIM $PRIMARY
write "}"
newline
newline
write "message ${MESSAGE}_value {"
writeFields $FIELDS $METAS $DELIM $OTHER
write "}"




